# Generated by Django 3.0.6 on 2020-05-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200515_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='history',
            field=models.CharField(default=b'\x80\x04]\x94.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watchlist',
            field=models.TextField(default=b'\x80\x04]\x94.'),
        ),
    ]
