# Generated by Django 3.0.6 on 2020-05-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_genre'),
        ('users', '0003_auto_20200516_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='history',
        ),
        migrations.AddField(
            model_name='profile',
            name='history',
            field=models.ManyToManyField(related_name='history', to='movie.Movie'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='profile',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchlist', to='movie.Movie'),
        ),
    ]
