# Generated by Django 3.0.6 on 2020-05-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_genre'),
        ('users', '0004_auto_20200516_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='history', to='movie.Movie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to='movie.Movie'),
        ),
    ]
