# Generated by Django 3.0.6 on 2020-05-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_genre'),
        ('users', '0006_auto_20200516_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='history', through='users.ThroughModel', to='movie.Movie'),
        ),
    ]
