# Generated by Django 3.0.6 on 2020-05-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=256)),
                ('info', models.CharField(max_length=512)),
                ('story', models.CharField(max_length=1024)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
